---
- hosts: localhost
  connection: local
  tasks:

    - name: Remove a resource
      azure_rm_resourcegroup:
        name: table6fy_devopswebrg
        location: koreacentral
        state: absent
        force: yes
