---
- hosts: localhost
  connection: local
  tasks:

    - name: Remove a resource
      azure_rm_resourcegroup:
        name: table6fyansibletest
        location: koreacentral
        state: absent
