---
- name: Create  VM
  hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ group_name }}"
      location: koreacentral
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ group_name }}"
      name: "{{ nsg_name }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - include_tasks: vm_details.yml
    loop:
      - { name: 'one', tag: 'nginx' }
      - { name: 'two', tag: 'apache' }
    loop_control:
      loop_var: vm 
